spring:
  application:
    name: restaurant-review

  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_review?useSSL=false
    username: root
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

logging:
  level:
    org:
      hibernate: ERROR